### ISSUE TITLE
Offline Documentation

### ISSUE THREAD

**Issue by Morabaraba** [qiciengine/qiciengine-documentation#1]
Hi,

Sorry if it is obvious, but how do you build the documentation for offline viewing?

**Comment by Morabaraba** [comment]
It uses gitbook and have the following npm scripts

``` sh
npm run-script install-zh
npm run-script install-en
npm run-script init-zh
npm run-script init-en
npm run-script build-api-zn
npm run-script build-manual-zn
npm run-script build-api-en
npm run-script build-manual-en
```

**Comment by huhudage** [comment]
You can also use 'npm run' instead :)

**Comment by Morabaraba** [comment]
True, but I was skimming through documentation late at night and missed the alias on the fifth line :smile: maybe I like the vebosity of `npm run-script` more, maybe...

https://docs.npmjs.com/cli/run-script
